use_frameworks!

platform :ios, '10.0'
target 'TagCollectionView_Example' do
  pod 'TagCollectionView', :path => '~/TagCollectionView'

  target 'TagCollectionView_Tests' do
    inherit! :search_paths

    
  end
end
